"""DevKitScaffold."""
from __future__ import annotations

import ast
import hashlib
import json
import os
from dataclasses import dataclass, field
from typing import Any

from aios.devkit.contracts import ProjectTemplate, ScaffoldConfig

# Maps a DevArtifact kind to the AIOS layer its skeleton lives in. The layer
# drives the architecture guard classification (T063) so generated files are
# verified against the correct allow-list.
KIND_LAYER: dict[str, str] = {
    "capability": "capability",
    "agent": "agent",
    "tool": "tool",
    "workflow": "runtime",
}

VALID_KINDS = tuple(KIND_LAYER)


@dataclass
class GeneratedFile:
    path: str
    code: str
    module_path: str


@dataclass
class ScaffoldArtifact:
    kind: str
    name: str
    version: str
    author: str
    template_version: str
    files: list[GeneratedFile] = field(default_factory=list)
    spec: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "name": self.name,
            "version": self.version,
            "author": self.author,
            "template_version": self.template_version,
            "conforms_to": {"architecture": "1.0", "contract": "1.0"},
            "files": [
                {"path": f.path, "code": f.code, "module_path": f.module_path}
                for f in self.files
            ],
            "spec": self.spec,
        }


_TEMPLATE_VERSION = "1.0.0"


def _class_name(name: str) -> str:
    return "".join(p.capitalize() for p in name.replace("-", "_").split("_")) or "Generated"


def _deterministic_spec_id(name: str, version: str) -> str:
    return hashlib.sha256(f"{name}:{version}".encode("utf-8")).hexdigest()[:12]


def _skeleton_code(kind: str, name: str, version: str) -> str:
    """Return architecture-clean skeleton source for a given kind.

    Generated code imports only stdlib (``unknown`` layer) so it passes the
    architecture guard (no ARCH-001..004) regardless of its layer.
    """
    cls = _class_name(name)
    if kind == "capability":
        return (
            f'"""AIOS capability skeleton: {name} (generated by aios devkit)."""\n'
            "from __future__ import annotations\n\n"
            "from dataclasses import dataclass\n\n\n"
            f"@dataclass\n"
            f"class {cls}Capability:\n"
            f'    name: str = "{name}"\n'
            f'    version: str = "{version}"\n'
            '    description: str = "Generated capability skeleton."\n'
        )
    if kind == "tool":
        return (
            f'"""AIOS tool skeleton: {name} (generated by aios devkit)."""\n'
            "from __future__ import annotations\n\n\n"
            f"class {cls}Tool:\n"
            f'    name: str = "{name}"\n'
            f'    version: str = "{version}"\n'
        )
    if kind == "agent":
        return (
            f'"""AIOS agent skeleton: {name} (generated by aios devkit)."""\n'
            "from __future__ import annotations\n\n\n"
            f"class {cls}Agent:\n"
            f'    name: str = "{name}"\n'
            f'    version: str = "{version}"\n'
        )
    # workflow
    return (
        f'"""AIOS workflow skeleton: {name} (generated by aios devkit)."""\n'
        "from __future__ import annotations\n\n\n"
        f"WORKFLOW_NAME = \"{name}\"\n"
        f"WORKFLOW_VERSION = \"{version}\"\n"
    )


def _collect_imports(code: str) -> list[str]:
    """Return the list of imported module names in a source string."""
    try:
        tree = ast.parse(code)
    except SyntaxError:
        return []
    targets: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            targets.extend(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            targets.append(node.module or "")
    return targets


class DevKitScaffold:
    def __init__(self) -> None:
        self._templates: dict[str, ProjectTemplate] = {}

    def register_template(self, template: ProjectTemplate) -> None:
        self._templates[template.name] = template

    def get_template(self, name: str) -> ProjectTemplate | None: return self._templates.get(name)

    def scaffold(self, config: ScaffoldConfig) -> dict:
        template = self._templates.get(config.template, ProjectTemplate(name=config.template))
        return {"project": config.project_name, "template": template.name, "files": template.files, "status": "created"}

    def list_templates(self) -> list[ProjectTemplate]: return list(self._templates.values())

    # --- T071: architecture/contract-conforming DevArtifacts -----------------

    def scaffold_artifact(
        self,
        kind: str,
        name: str,
        version: str = "1.0.0",
        author: str = "",
    ) -> ScaffoldArtifact:
        """Generate a capability/agent/tool/workflow skeleton conforming to
        Architecture 1.0 (T063) and Contract 1.0 (T064).

        Deterministic: identical ``(kind, name, version)`` always yields
        byte-identical output (no randomness, stable spec id).
        """
        if kind not in KIND_LAYER:
            from aios.devkit.errors import ActionableError
            raise ActionableError(
                f"Unknown artifact kind: {kind!r}",
                cause="Kind is not one of capability/agent/tool/workflow.",
                fix_hint=f"Use one of: {', '.join(VALID_KINDS)}.",
            )
        layer = KIND_LAYER[kind]
        code = _skeleton_code(kind, name, version)
        module_path = f"aios/{layer}/{name}.py"
        file_path = f"aios/{layer}/{name}.py"
        spec_id = _deterministic_spec_id(name, version)
        spec = {
            "spec_id": spec_id,
            "kind": kind,
            "name": name,
            "version": version,
            "capabilities": [{"name": name, "version": version}],
        }
        spec_json = json.dumps(spec, sort_keys=True, indent=2)
        readme = (
            f"# {name}\n\n"
            f"Generated {kind} skeleton (AIOS 1.0 DX).\n\n"
            f"- Architecture: 1.0 (T063)\n"
            f"- Contract: 1.0 (T064)\n"
            f"- Template version: {_TEMPLATE_VERSION}\n"
        )
        files = [
            GeneratedFile(path=file_path, code=code, module_path=module_path),
            GeneratedFile(path="extension_spec.json", code=spec_json, module_path="extension_spec.json"),
            GeneratedFile(path="README.md", code=readme, module_path="README.md"),
        ]
        return ScaffoldArtifact(
            kind=kind,
            name=name,
            version=version,
            author=author,
            template_version=_TEMPLATE_VERSION,
            files=files,
            spec=spec,
        )

    def verify_conformance(self, artifact: ScaffoldArtifact) -> dict[str, Any]:
        """Verify an artifact against Architecture 1.0 (T063) + Contract 1.0 (T064).

        Runs the real governance architecture guard over the generated sources
        and the extension contract validator over the generated spec. Returns a
        structured result with ``passed``.
        """
        from aios.extension_contracts.contracts import CapabilityExport, ExtensionSpec
        from aios.extension_contracts.validator import ExtensionValidator
        from aios.governance.architecture.guard import ArchitectureGuard

        py_files = [f for f in artifact.files if f.path.endswith(".py")]
        sources = [(f.code, f.module_path) for f in py_files]
        arch = ArchitectureGuard().check(sources=sources)

        spec = ExtensionSpec(
            spec_id=artifact.spec.get("spec_id", ""),
            name=artifact.spec.get("name", ""),
            version=artifact.spec.get("version", ""),
            capabilities=[
                CapabilityExport(name=c.get("name", ""), version=c.get("version", ""))
                for c in artifact.spec.get("capabilities", [])
            ],
        )
        validator = ExtensionValidator()
        contract = validator.validate_spec(spec)

        imported: list[str] = []
        for f in py_files:
            imported.extend(_collect_imports(f.code))
        boundary = validator.check_boundary(spec, imported)

        passed = arch.passed and contract["valid"] and boundary["valid"]
        return {
            "passed": passed,
            "architecture": {"passed": arch.passed, "violations": [v.__dict__ for v in arch.violations]},
            "contract": {"valid": contract["valid"], "errors": contract["errors"]},
            "boundary": {"valid": boundary["valid"], "violations": boundary["violations"]},
        }

    def render(self, artifact: ScaffoldArtifact, base_dir: str) -> list[str]:
        """Write an artifact's files to ``base_dir`` and return written paths."""
        written: list[str] = []
        for f in artifact.files:
            target = os.path.join(base_dir, f.path)
            os.makedirs(os.path.dirname(target), exist_ok=True)
            with open(target, "w", encoding="utf-8") as fh:
                fh.write(f.code)
            written.append(target)
        return written
