"""Command-line interface for the local CI/CD checker.

Subcommands
-----------
  check          Run the CI checks and print a report (manual use)
  run            Same as check, but minimal output — intended for git hooks
  install-hook   Install a git pre-push (or pre-commit) hook that runs `run`
  uninstall-hook Remove a previously installed hook

Invoked from the ``aiagent`` entry point (``aiagent ci ...``) or directly via
``python -m aios.ci ...``.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

from aios.ci.checker import REPO_ROOT, run_ci_check

_HOOK_MARKER = "AIOS CI"


def _hook_script(scope: str) -> str:
    return (
        "#!/bin/sh\n"
        f"# {_HOOK_MARKER} pre-push gate — generated by `aiagent ci install-hook`.\n"
        "# Fail-closed: blocks the push when local CI checks fail.\n"
        "set -e\n"
        f'echo "[aios-ci] Running local CI gate (scope={scope})..."\n'
        f"python -m aios.ci run --scope {scope} --quiet\n"
        "RC=$?\n"
        'if [ $RC -ne 0 ]; then\n'
        '  echo "[aios-ci] FAILED (exit $RC) — push blocked. Run \'aiagent ci check\' to inspect."\n'
        "  exit 1\n"
        "fi\n"
        'echo "[aios-ci] OK — proceed with push."\n'
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="aiagent ci", description="Local CI/CD checker")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_check = sub.add_parser("check", help="Run CI checks and print a report")
    p_check.add_argument("--scope", choices=["core", "full"], default="full")
    p_check.add_argument("--timeout", type=float, default=None, help="Per-step timeout (seconds)")
    p_check.add_argument("--quiet", action="store_true", help="Only print the OVERALL line")
    p_check.add_argument("--json", action="store_true", help="Emit JSON instead of text")
    p_check.set_defaults(func=_cmd_check)

    p_run = sub.add_parser("run", help="Run CI checks (designed for git hooks)")
    p_run.add_argument("--scope", choices=["core", "full"], default="full")
    p_run.add_argument("--timeout", type=float, default=None)
    p_run.add_argument("--quiet", action="store_true")
    p_run.set_defaults(func=_cmd_check)

    p_hook = sub.add_parser("install-hook", help="Install a git hook that runs the CI gate")
    p_hook.add_argument("--hook-type", choices=["pre-push", "pre-commit"], default="pre-push")
    p_hook.add_argument("--scope", choices=["core", "full"], default="full")
    p_hook.set_defaults(func=_cmd_install_hook)

    p_unhook = sub.add_parser("uninstall-hook", help="Remove a previously installed git hook")
    p_unhook.add_argument("--hook-type", choices=["pre-push", "pre-commit"], default="pre-push")
    p_unhook.set_defaults(func=_cmd_uninstall_hook)

    return parser


def _cmd_check(args: argparse.Namespace) -> int:
    report = run_ci_check(scope=args.scope, timeout=args.timeout)
    if getattr(args, "json", False):
        print(json.dumps(report.to_dict(), indent=2))
    elif args.quiet:
        print(f"OVERALL: {report.overall.value.upper()}")
    else:
        report.print()
    return 0 if report.overall.ok else 1


def _cmd_install_hook(args: argparse.Namespace) -> int:
    hook_dir = REPO_ROOT / ".git" / "hooks"
    if not hook_dir.is_dir():
        print("ERROR: not a git repository (missing .git/hooks)", file=sys.stderr)
        return 2
    hook_path = hook_dir / args.hook_type
    if hook_path.exists():
        backup = hook_path.with_name(f"{args.hook_type}.bak")
        hook_path.replace(backup)
        print(f"backed up existing {args.hook_type} hook -> {backup.name}")
    hook_path.write_text(_hook_script(args.scope))
    try:
        os.chmod(hook_path, 0o755)
    except OSError:
        pass  # chmod is best-effort (no-op on Windows)
    print(f"installed {args.hook_type} hook at {hook_path}")
    return 0


def _cmd_uninstall_hook(args: argparse.Namespace) -> int:
    hook_path = REPO_ROOT / ".git" / "hooks" / args.hook_type
    if not hook_path.exists():
        print(f"no {args.hook_type} hook found")
        return 0
    if _HOOK_MARKER not in hook_path.read_text(errors="ignore"):
        print(f"refusing to remove non-{_HOOK_MARKER} {args.hook_type} hook", file=sys.stderr)
        return 1
    hook_path.unlink()
    print(f"removed {args.hook_type} hook")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
