// Auto-generated by aios.tool.website.n5_builder — UI wiring + pure logic (Node-testable).
(function () {
  "use strict";

  // ---------- Pure logic (no DOM; exported for Node harness) ----------
  function filterVocab(vocab, query, topic) {
    query = (query || "").toLowerCase();
    return vocab.filter(function (v) {
      if (topic && topic !== "all" && v[3] !== topic) return false;
      if (!query) return true;
      return (v[0] + " " + v[1] + " " + v[2]).toLowerCase().indexOf(query) !== -1;
    });
  }

  function makeRng(seed) {
    var s = seed >>> 0 || 1;
    return function () { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; };
  }

  function shuffle(arr, rng) {
    for (var i = arr.length - 1; i > 0; i--) {
      var j = Math.floor(rng() * (i + 1));
      var t = arr[i]; arr[i] = arr[j]; arr[j] = t;
    }
    return arr;
  }

  function generateQuiz(vocab, n, seed) {
    var rng = makeRng(seed || 1);
    var pool = vocab.slice();
    var questions = [];
    n = Math.min(n || 5, pool.length);
    for (var i = 0; i < n; i++) {
      var idx = Math.floor(rng() * pool.length);
      var word = pool.splice(idx, 1)[0];
      var options = [word[2]];
      while (options.length < 4 && pool.length) {
        var o = pool[Math.floor(rng() * pool.length)][2];
        if (options.indexOf(o) === -1) options.push(o);
      }
      questions.push({
        q: word[0] + " (" + word[1] + ")",
        answer: word[2],
        options: shuffle(options.slice(), rng),
      });
    }
    return questions;
  }

  function scoreQuiz(questions, answers) {
    var score = 0;
    for (var i = 0; i < questions.length; i++) {
      if (answers[i] === questions[i].answer) score++;
    }
    return score;
  }

  // ---------- DOM wiring (browser only) ----------
  function ready(fn) {
    if (document.readyState !== "loading") fn();
    else document.addEventListener("DOMContentLoaded", fn);
  }

  function renderKana() {
    var root = document.getElementById("kana");
    if (!root || typeof KANA === "undefined") return;
    root.innerHTML = "";
    KANA.forEach(function (group) {
      var wrap = document.createElement("div");
      wrap.className = "kana-group";
      var h = document.createElement("h2"); h.textContent = group.name || "Kana";
      wrap.appendChild(h);
      var grid = document.createElement("div"); grid.className = "kana-grid";
      group.rows.forEach(function (r) {
        var cell = document.createElement("div"); cell.className = "kana-cell";
        cell.innerHTML = '<div class="k">' + r[0] + '</div><div class="r">' + r[1] + "</div>";
        grid.appendChild(cell);
      });
      wrap.appendChild(grid); root.appendChild(wrap);
    });
  }

  function renderVocab() {
    var tbody = document.querySelector("#vocabTable tbody");
    var topicSel = document.getElementById("vocabTopic");
    if (!tbody || typeof VOCAB === "undefined") return;
    var topics = Array.from(new Set(VOCAB.map(function (v) { return v[3]; })));
    topicSel.innerHTML = '<option value="all">Tất cả</option>' +
      topics.map(function (t) { return '<option value="' + t + '">' + t + "</option>"; }).join("");
    function draw() {
      var q = document.getElementById("vocabSearch").value;
      var t = topicSel.value;
      var rows = filterVocab(VOCAB, q, t);
      tbody.innerHTML = rows.map(function (v) {
        return "<tr><td>" + v[0] + "</td><td>" + v[1] + "</td><td>" + v[2] + "</td><td>" + v[3] + "</td></tr>";
      }).join("");
    }
    document.getElementById("vocabSearch").addEventListener("input", draw);
    topicSel.addEventListener("change", draw);
    draw();
  }

  function renderGrammar() {
    var root = document.getElementById("grammar");
    if (!root || typeof GRAMMAR === "undefined") return;
    root.innerHTML = GRAMMAR.map(function (g) {
      return '<div class="kana-group"><h2>' + g.pattern + "</h2>" +
        '<div class="kana-cell"><div class="k">' + g.jp + '</div><div class="r">' + g.vn + "</div></div></div>";
    }).join("");
  }

  function startQuiz() {
    var body = document.getElementById("quizBody");
    var result = document.getElementById("quizResult");
    var questions = generateQuiz(VOCAB, 5, 7);
    var answers = [];
    body.innerHTML = "";
    questions.forEach(function (q, i) {
      var box = document.createElement("div"); box.className = "quiz-q";
      box.innerHTML = "<p><strong>" + (i + 1) + ". " + q.q + "</strong></p><div class='opts'></div>";
      var opts = box.querySelector(".opts");
      q.options.forEach(function (opt) {
        var b = document.createElement("button"); b.textContent = opt;
        b.addEventListener("click", function () {
          answers[i] = opt;
          Array.prototype.forEach.call(opts.children, function (c) { c.disabled = true; });
          b.classList.add(opt === q.answer ? "correct" : "wrong");
        });
        opts.appendChild(b);
      });
      body.appendChild(box);
    });
    var submit = document.createElement("button");
    submit.textContent = "Xem kết quả";
    submit.addEventListener("click", function () {
      var score = scoreQuiz(questions, answers);
      result.textContent = "Điểm: " + score + " / " + questions.length;
    });
    body.appendChild(submit);
  }

  function applyTheme(theme) {
    document.documentElement.setAttribute("data-theme", theme);
    var btn = document.getElementById("themeToggle");
    if (btn) btn.setAttribute("data-theme", theme);
  }

  function wireTabs() {
    document.querySelectorAll(".tab").forEach(function (tab) {
      tab.addEventListener("click", function () {
        document.querySelectorAll(".tab").forEach(function (t) { t.setAttribute("aria-selected", "false"); });
        tab.setAttribute("aria-selected", "true");
        document.querySelectorAll(".panel").forEach(function (p) { p.hidden = true; });
        document.getElementById(tab.dataset.tab).hidden = false;
      });
    });
  }

  if (typeof document !== "undefined") {
    ready(function () {
      renderKana(); renderVocab(); renderGrammar(); wireTabs();
      var tb = document.getElementById("startQuiz"); if (tb) tb.addEventListener("click", startQuiz);
      var tog = document.getElementById("themeToggle");
      if (tog) tog.addEventListener("click", function () {
        var cur = document.documentElement.getAttribute("data-theme");
        applyTheme(cur === "dark" ? "light" : "dark");
      });
    });
  }

  if (typeof module !== "undefined" && module.exports) {
    module.exports = {
      filterVocab: filterVocab, generateQuiz: generateQuiz, scoreQuiz: scoreQuiz,
    };
  }
})();
